bt_executor:
  muovi_sto_cannolo:
    group_name: "comau"
    ik_service_name: "/comau_ik_solver/get_ik"
    location_name: "test_comau_location"
    fjt_action_name: "/comau_scaled_fjt_controller/follow_joint_trajectory"
    simulation: False

  shakera_sto_babbà:
    group_name: "comau"
    trj_names: ["trj_comau"]
    fjt_action_name: "/comau_scaled_fjt_controller/follow_joint_trajectory"
    repetitions: 5
    recompute_time_law: False
    simulation: False

  spremi_sto_burger:
    group_name: "kuka"
    trj_names: ["trj_kuka"]
    fjt_action_name: "/kuka_scaled_fjt_controller/follow_joint_trajectory"
    repetitions: 5
    recompute_time_law: False
    simulation: False

